### ISSUE TITLE
2008 LIS Data can't be serialized to netCDF

### ISSUE THREAD

**Issue by lsetiawan** [NASA-Planetary-Science/HiMAT#67]
When trying to serialize the new 2008 LIS Data, I get HDF Error. See below.

```bash
[(Timestamp('2008-01-01 00:00:00'), Timestamp('2008-12-31 00:00:00'))]
Processing 2008...
Subsetting data...
Exporting /att/nobackup/lsetiawa/LISNEWYEAR/LIS_2008.nc
[                                        ] | 0% Completed | 20.5sHDF5-DIAG: Error detected in HDF5 (1.8.18) thread 140258733717248:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1372 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005: H5Zdeflate.c line 125 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 140258733717248:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1372 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005: H5Zdeflate.c line 125 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
[                                        ] | 0% Completed | 20.6s
Traceback (most recent call last):
  File "/home/lsetiawa/GitHub/HiMAT/himatpy/LIS/LISpreprocess.py", line 24, in <module>
    LISutils.process_lis_data(args.lisdir, args.outdir, args.startyear, args.endyear)
  File "/att/gpfsfs/home/lsetiawa/GitHub/HiMAT/himatpy/LIS/utils.py", line 175, in process_lis_data
    procds.to_netcdf(outname)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/core/dataset.py", line 977, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/backends/api.py", line 573, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/core/dataset.py", line 918, in dump_to_store
    store.sync()
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 336, in sync
    super(NetCDF4DataStore, self).sync()
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/backends/common.py", line 202, in sync
    self.writer.sync()
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/backends/common.py", line 179, in sync
    da.store(self.sources, self.targets, lock=GLOBAL_LOCK)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/array/core.py", line 900, in store
    Array._get(dsk, keys, **kwargs)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/base.py", line 106, in _get
    return get(dsk2, keys, **kwargs)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/compatibility.py", line 60, in reraise
    raise exc
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/dask/array/core.py", line 72, in getter
    c = np.asarray(c)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/core/indexing.py", line 408, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/core/indexing.py", line 375, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/conventions.py", line 367, in __getitem__
    self.scale_factor, self.add_offset, self._dtype)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/conventions.py", line 63, in mask_and_scale
    values = np.array(array, dtype=dtype, copy=True)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/core/indexing.py", line 375, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/lsetiawa/miniconda/envs/himat/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 60, in __getitem__
    data = getitem(self.get_array(), key)
  File "netCDF4/_netCDF4.pyx", line 3803, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 4657, in netCDF4._netCDF4.Variable._get
  File "netCDF4/_netCDF4.pyx", line 1556, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

**Comment by lsetiawan** [comment]
Same error also occurs when trying to manually add the 2008 dataset to the rest of the dataset. 

```python
allds = xr.merge([ds, procds]) # procds is the 2008 dataset
```

```python
netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable._get()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

RuntimeError: NetCDF: HDF error
```

**Comment by lsetiawan** [comment]
After the update by Yeosang to the 2008 LIS Datasets. Things work great now. I was able to make the Yearly netCDF. Closing.
